name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  release:
    environment: pypi
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pip and nox
        run: |
          pip install --upgrade pip nox uv
          pip --version
          nox --version
          uv --version

      - name: Build package
        run: nox -s build-3.13

      - name: Upload package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
